version: '3.8'
services:
  django:
    container_name: django
    build: ./requirements/django
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:admin_password@postgres:5432/transcendencedb
      - DB_HOST=postgres
      - DB_PORT=5432
      - API42_ID='u-s4t2ud-7d3469743fce1585b0910d91a8413cf0568b22637c674dc881a72d4d1f105c4d'
      - API42_SECRET='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'
    env_file:
    	- .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./requirements/django:/app
    networks:
      - transcendence

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: transcendencedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d transcendencedb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pong:
    container_name: pong
    build: ./requirements/pong
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://admin:admin_password@postgres:5432/transcendencedb
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - transcendence

volumes:
  postgres_data:

networks:
  transcendence:
