services:
  django:
    container_name: django
    build: ./requirements/django
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://admin:admin_password@postgres:5432/transcendencedb
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
    volumes:
      - ./requirements/django:/app
    networks:
      - transcendence

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: transcendencedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence

volumes:
  postgres_data:

networks:
  transcendence:
