# Generated by Django 5.1.5 on 2025-01-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExampleModel',
            new_name='MyModel',
        ),
    ]
