# Generated by Django 5.1.5 on 2025-01-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusertrans',
            name='image',
        ),
        migrations.AddField(
            model_name='customusertrans',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
