# Generated by Django 5.1.5 on 2025-01-31 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0002_remove_customusertrans_image_customusertrans_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusertrans',
            name='photo',
        ),
    ]
