# Generated by Django 5.1.5 on 2025-01-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0003_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='score',
            new_name='score1',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='score_2',
            new_name='score2',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='user',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='user_2',
            new_name='user2',
        ),
    ]
