# Generated by Django 5.1.5 on 2025-01-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0003_remove_customusertrans_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusertrans',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
