# Generated by Django 5.1.5 on 2025-01-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0004_customusertrans_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusertrans',
            name='photo',
            field=models.ImageField(upload_to='users/images/'),
        ),
    ]
