# Generated by Django 5.1.5 on 2025-01-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0004_rename_score_history_score1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='status',
        ),
        migrations.AddField(
            model_name='history',
            name='winner',
            field=models.IntegerField(default=0),
        ),
    ]
