# Generated by Django 5.1.5 on 2025-01-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0005_remove_history_status_history_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusertrans',
            name='mmr',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='customusertrans',
            name='nbrgames',
            field=models.IntegerField(default=0),
        ),
    ]
