# Generated by Django 5.1.5 on 2025-02-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0005_alter_customusertrans_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusertrans',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
