# Generated by Django 5.1.5 on 2025-01-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0006_customusertrans_mmr_customusertrans_nbrgames'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusertrans',
            name='loses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customusertrans',
            name='null',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customusertrans',
            name='percent_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customusertrans',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
