# Generated by Django 5.1.5 on 2025-01-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0007_customusertrans_loses_customusertrans_null_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusertrans',
            name='loses',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='customusertrans',
            name='mmr',
            field=models.IntegerField(default=1000, editable=False),
        ),
        migrations.AlterField(
            model_name='customusertrans',
            name='nbrgames',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='customusertrans',
            name='null',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='customusertrans',
            name='percent_win',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='customusertrans',
            name='wins',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
